export interface Tool {
  id: string;
  name: string;
  slug: string;
  category: string;
  description: string;
}

export const TOOLS: Tool[] = [
  {
    id: "json-beautifier",
    name: "JSON Beautifier",
    slug: "json-beautifier",
    category: "Beautifiers & Minifiers",
    description: "Format, beautify, and validate JSON code online for better readability.",
  },
  {
    id: "css-minifier",
    name: "CSS Minifier",
    slug: "css-minifier",
    category: "Beautifiers & Minifiers",
    description: "Compress and minify CSS code by removing white spaces and comments.",
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON Converter",
    slug: "csv-to-json",
    category: "Converters",
    description: "Convert CSV data into clean, structured JSON format instantly.",
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder & Decoder",
    slug: "base64-encoder-decoder",
    category: "Utilities & Encoders",
    description: "Encode text strings or decode Base64 strings safely online.",
  },
  {
    id: "sip-calculator",
    name: "SIP Calculator",
    slug: "sip-calculator",
    category: "Finance Calculators",
    description: "Calculate expected returns on your Systematic Investment Plan (SIP) investments.",
  },
  {
    id: "json-validator",
    name: "JSON Validator",
    slug: "json-validator",
    category: "Validators", // <--- Updated category
    description: "Validate JSON structure online and detect syntax errors instantly.",
  },
  {
    id: "js-beautifier",
    name: "JavaScript Beautifier",
    slug: "js-beautifier",
    category: "Beautifiers & Minifiers",
    description: "Format, beautify, and un-minify obfuscated JavaScript code for better readability.",
  },
  {
    id: "csv-to-html-table",
    name: "CSV to HTML Table Converter",
    slug: "csv-to-html-table",
    category: "Converters",
    description: "Convert raw CSV spreadsheet data into semantic, structured HTML table elements instantly.",
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG Converter",
    slug: "png-to-jpg-converter",
    category: "Image Converters",
    description: "Convert PNG images to JPG format online for free with quality control and smaller file sizes.",
  },
  {
    id: "my-ip-finder",
    name: "My IP Address Finder",
    slug: "my-ip-finder",
    category: "IP & Domain",
    description: "Instantly find your public IPv4/IPv6 address, ISP details, network organization, and geographic location.",
  },
  {
    id: "dns-lookup",
    name: "Online DNS Lookup Tool",
    slug: "dns-lookup",
    category: "IP & Domain",
    description: "Perform quick DNS record lookups for A, AAAA, MX, TXT, NS, and CNAME records of any domain.",
  },
  {
    id: "domain-age-checker",
    name: "Domain Age & Expiry Checker",
    slug: "domain-age-checker",
    category: "IP & Domain",
    description: "Check exact domain creation date, expiration date, age, and registrar information instantly.",
  },
  {
    id: "ip-subnet-calculator",
    name: "IP Subnet Calculator",
    slug: "ip-subnet-calculator",
    category: "IP & Domain",
    description: "Calculate network address, subnet mask, broadcast address, and usable host ranges for CIDR notation.",
  },
  {
    id: "ssl-checker",
    name: "SSL Certificate Checker",
    slug: "ssl-checker",
    category: "IP & Domain",
    description: "Check SSL/TLS certificate validity, issuer information, active status, and remaining days before expiration.",
  },
  {
    id: "html-minifier",
    name: "HTML Minifier",
    slug: "html-minifier",
    category: "Beautifiers & Minifiers",
    description: "Compress HTML markup by stripping out whitespace, unnecessary comments, and line breaks to boost page load speed.",
  },
  {
    id: "html-beautifier",
    name: "HTML Beautifier",
    slug: "html-beautifier",
    category: "Beautifiers & Minifiers",
    description: "Format and indent messy or minified HTML code with clean spacing and proper DOM tag structure.",
  },
  {
    id: "javascript-minifier",
    name: "JavaScript Minifier",
    slug: "javascript-minifier",
    category: "Beautifiers & Minifiers",
    description: "Compress JS code by removing comments, whitespace, and unnecessary formatting to reduce script load times.",
  },
  {
    id: "javascript-obfuscator",
    name: "JavaScript Obfuscator",
    slug: "javascript-obfuscator",
    category: "Beautifiers & Minifiers",
    description: "Protect client-side JavaScript code by turning readable script logic into unreadable obfuscated syntax.",
  },
  {
    id: "json-minifier",
    name: "JSON Minifier",
    slug: "json-minifier",
    category: "Beautifiers & Minifiers",
    description: "Compress JSON strings by removing extra spaces, indentations, and newlines to optimize payload sizes.",
  },
  {
    id: "xml-beautifier",
    name: "XML Beautifier",
    slug: "xml-beautifier",
    category: "Beautifiers & Minifiers",
    description: "Format, indent, and validate unorganized XML data to make it structured and human-readable.",
  },
  {
    id: "xml-minifier",
    name: "XML Minifier",
    slug: "xml-minifier",
    category: "Beautifiers & Minifiers",
    description: "Compress XML files by stripping whitespace, comments, and line breaks to decrease payload sizes.",
  },
  {
    id: "opml-beautifier",
    name: "OPML Beautifier",
    slug: "opml-beautifier",
    category: "Beautifiers & Minifiers",
    description: "Format, indent, and validate unorganized OPML outline structures to make RSS feed exports human-readable.",
  },
  {
    id: "opml-minifier",
    name: "OPML Minifier",
    slug: "opml-minifier",
    category: "Beautifiers & Minifiers",
    description: "Compress OPML files by stripping whitespace, comments, and line breaks to decrease payload sizes.",
  },
  {
    id: "sql-beautifier",
    name: "SQL Beautifier",
    slug: "sql-beautifier",
    category: "Beautifiers & Minifiers",
    description: "Format, capitalize keywords, and structure raw SQL queries for improved readability and debugging.",
  },
  {
    id: "sql-minifier",
    name: "SQL Minifier",
    slug: "sql-minifier",
    category: "Beautifiers & Minifiers",
    description: "Compress SQL statements by removing unnecessary comments, line breaks, and whitespace intervals.",
  },
  {
    id: "image-to-prompt",
    name: "Image to Prompt Generator",
    slug: "image-to-prompt",
    category: "AI & Multimedia Tools",
    description: "Upload any image and generate detailed Midjourney, DALL-E 3, and Stable Diffusion prompts instantly.",
  },
  {
    id: "svg-to-react",
    name: "SVG to React TSX Converter",
    slug: "svg-to-react",
    category: "Converters",
    description: "Transform raw SVG vector code into production-ready React (TSX) functional components instantly.",
  },
  {
    id: "crypto-wallet-checker",
    name: "Crypto Wallet Address Checker",
    slug: "crypto-wallet-checker",
    category: "Crypto & Network Utilities",
    description: "Instantly detect the blockchain network, native symbol, and address type for any cryptocurrency wallet address.",
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image Converter",
    slug: "pdf-to-image",
    category: "Converters",
    description: "Convert PDF pages into high-quality PNG or JPEG images directly inside your browser.",
  },
  {
    id: "image-converter-compressor",
    name: "Image Compressor",
    slug: "image-converter-compressor",
    category: "Compression",
    description: "Convert and compress PNG, JPG, WebP images instantly inside your browser. 100% free and private.",
  },
  {
    id: "bio-link-generator",
    name: "Bio Link & Social Profile Generator",
    slug: "bio-link-generator",
    category: "Utilities",
    description: "Create a custom mobile-ready bio link landing page for Instagram, TikTok, and Twitter in seconds.",
  },
  {
    id: "emi-calculator",
    name: "EMI Calculator",
    slug: "emi-calculator",
    category: "Finance Calculators",
    description: "Calculate your monthly home, car, or personal loan EMIs instantly with interactive sliders and visual breakdown.",
  },
  {
    id: "css-validator",
    name: "CSS Validator",
    slug: "css-validator",
    category: "Validators",
    description: "Validate your CSS code instantly to catch syntax errors, missing brackets, unclosed quotes, and bad properties.",
  },
  {
    id: "javascript-validator",
    name: "JavaScript Validator",
    slug: "javascript-validator",
    category: "Validators",
    description: "Validate JavaScript code online to catch syntax errors, unclosed brackets, and bad statements instantly.",
  },
  {
    id: "xml-validator",
    name: "XML Validator",
    slug: "xml-validator",
    category: "Validators",
    description: "Validate XML structure online, check well-formedness, and detect tag closing or syntax errors instantly.",
  },
  {
    id: "yaml-validator",
    name: "YAML Validator",
    slug: "yaml-validator",
    category: "Validators",
    description: "Validate YAML structure online, detect indentation mistakes, missing colons, and syntax errors instantly.",
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG Converter",
    slug: "heic-to-jpg",
    category: "Image Converters",
    description: "Convert Apple HEIC photos to standard JPG format instantly in your browser without quality loss.",
  },
  {
    id: "random-password-generator",
    name: "Random Password Generator",
    slug: "random-password-generator",
    category: "Utilities",
    description: "Generate strong, secure, and customizable random passwords instantly to protect your accounts.",
  },
  {
    id: "images-to-pdf",
    name: "Images to PDF Converter",
    slug: "images-to-pdf",
    category: "Converters",
    description: "Combine multiple JPG, PNG, or WebP images into a single professional PDF document instantly.",
  },
  {
    id: "docs-to-pdf",
    name: "Word to PDF Converter",
    slug: "docs-to-pdf",
    category: "Converters",
    description: "Convert Word documents (.docx) and text files into professional PDF files directly in your browser.",
  },
  {
    id: "txt-to-pdf",
    name: "TXT to PDF Converter",
    slug: "txt-to-pdf",
    category: "Converters",
    description: "Convert plain text (.txt) files or raw text into clean, formatted PDF documents directly in your browser.",
  },
  {
    id: "pdf-to-docx",
    name: "PDF to Word Converter",
    slug: "pdf-to-docx",
    category: "Converters",
    description: "Extract text from PDF documents and download them as fully formatted Word (.docx) files instantly.",
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    slug: "unlock-pdf",
    category: "Documents",
    description: "Remove passwords and security restrictions from PDF files instantly and securely inside your browser.",
  },
  {
    id: "compress-pdf",
    name: "PDF Compressor",
    slug: "compress-pdf",
    category: "Compression",
    description: "Reduce PDF file size quickly and securely directly in your browser without losing quality.",
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF Converter",
    slug: "excel-to-pdf",
    category: "Documents",
    description: "Convert Excel spreadsheets (.xlsx, .xls) into clean, printable PDF documents directly in your browser.",
  },
  {
    id: "python-online-compiler",
    name: "Python Online Compiler",
    slug: "python-online-compiler",
    category: "Development",
    description: "Write, test, and execute Python 3 code instantly inside your browser without any setup.",
  },
  {
    id: "global-income-tax-calculator",
    name: "Income Tax Calculator",
    slug: "income-tax-calculator",
    category: "Finance Calculators",
    description: "Calculate your estimated income tax, net salary, and tax breakdown across multiple countries.",
  },
  {
    id: "regex-tester",
    name: "Regex Tester & Debugger",
    slug: "regex-tester",
    category: "Development",
    description: "Test, debug, and evaluate regular expressions with real-time matching, flags, and replacement.",
  },
  {
    id: "site-ip-checker",
    name: "Site IP Checker",
    slug: "site-ip-checker",
    category: "IP & Domain",
    description: "Find the IP address, hosting location, and server details of any domain name instantly.",
  },
];

// DYNAMIC CATEGORIES: Jo bhi category TOOLS array me hogi, auto-extract ho jayegi
export const CATEGORIES = Array.from(
  new Set(TOOLS.map((tool) => tool.category))
);